version: '3'

services:
  postgres:
    image: postgis/postgis:15-3.3
    # Provide the password for postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=remix
    # Set health checks to wait until postgres has started
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432

  web:
    build:
      context: .
      target: dev
    # Set environment variables for the web service
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/remix'
      SESSION_SECRET: super-duper-s3cret
      NODE_VERSION: 18
    depends_on:
      - postgres
    ports:
      - 80:3000
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/healthcheck']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
