version: '3'

services:
  web:
    container_name: dms-web-test
    image: crdmsdevwesteurope.azurecr.io/data-management-suite/web:test
    pull_policy: always
    restart: unless-stopped
    env_file:
      - ./test.env
    ports:
      - 80:80
    labels:
      com.datadoghq.ad.logs: '[{"source": "nodejs", "service": "data-management-suite", "env": "test"}]'
      com.centurylinklabs.watchtower.enable: 'true'

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --cleanup --label-enable --include-stopped
    env_file:
      - ./watchtower.env

  datadog-agent:
    container_name: datadog-agent
    image: datadog/agent:latest
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /proc/:/host/proc/:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    environment:
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_CONTAINER_LABELS_AS_TAGS=true
      - DD_CONTAINER_EXCLUDE=name:datadog-agent
      - DD_SITE=datadoghq.com
      - DD_ENV=test
      - DD_SERVICE=data-management-suite
    env_file:
      - ./dd.env
    labels:
      com.centurylinklabs.watchtower.enable: 'false'
