site_name: 'Deltares Datasuite Python SDK'
site_url: https://datasuite.deltares.nl/docs
repo_url: https://github.com/Deltares-research/data-management-suite
edit_uri: 'edit/main/utils/deltares_datasuite/docs/'
theme:
  name: material
  features:
    - navigation.footer
    - content.action.edit
    - content.action.view
    - content.copy.code
  palette:
    primary: black
  favicon: /favicon.ico
  icon:
    logo: material/library
extra:
  generator: false
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            preload_modules:
              - pystac
  - autorefs
  - tags
  - macros

nav:
  - Home: 'index.md'
  - User Guide: 'guide.md'
  - Classes:
      - DataManagementSuiteClient: 'classes/client.md'
      - DataManagementSuiteItem: 'classes/item.md'
  - Back to the App: '/app/items'
  - Issue Tracker: 'https://github.com/Deltares-research/data-management-suite/issues'
