on:
  push:
    paths:
      - utils/deltares_datasuite/**
      - '.github/workflows/**'
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Release Python package

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          release-type: python
          path: utils/deltares_datasuite
          package-name: deltares-datasuite
          monorepo-tags: true
      - name: Release python package to PyPi with poetry
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          make poetry-download
          poetry publish --build
