on:
  push:
    branches:
      - main

permissions:
  # This permission is required for trusted publishing.
  id-token: write
  contents: write
  pull-requests: write

name: Release packages

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          monorepo-tags: true
      - run: echo "A release was created."
        if: ${{ steps.release.outputs.releases_created }}

      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.releases_created }}

      - name: Mint token
        if: ${{ steps.release.outputs['utils/deltares_datasuite--release_created'] }}
        id: mint
        uses: tschm/token-mint-action@v1.0.2

      - name: Release python package to PyPi with poetry
        if: ${{ steps.release.outputs['utils/deltares_datasuite--release_created'] }}
        working-directory: ./utils/deltares_datasuite
        run: |
          make poetry-download
          poetry publish -u __token__ -p '${{ steps.mint.outputs.api-token }}' --build

      - name: Add python files to release
        if: ${{ steps.release.outputs['utils/deltares_datasuite--release_created'] }}
        working-directory: ./utils/deltares_datasuite
        run: |
          gh release upload ${{ steps.release.outputs['utils/deltares_datasuite--tag_name'] }} .dist/*

      - name: Build image and push tag after web release
        # We push tags here because tags pushed by release-please do not trigger the tag-images workflow
        if: ${{ steps.release.outputs['.--release_created'] }}
        env:
          FULL_IMAGE_TO_PUSH_W_TAG: ${{ vars.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/data-management-suite/web
        run: |
          az acr login --name ${{ vars.AZURE_CONTAINER_REGISTRY_NAME }}
          TAG_TO_PUSH=$(echo "${{ steps.release.outputs['.--tag_name']}}"| awk '{split($0,a,"web-"); print a[2]}')
          echo "TAG_TO_PUSH: $TAG_TO_PUSH"
          docker buildx build --platform linux/amd64 --tag ${{ env.FULL_IMAGE_TO_PUSH_W_TAG }}:${{ github.sha }} --tag ${{ env.FULL_IMAGE_TO_PUSH_W_TAG }}:$TAG_TO_PUSH --push .
